services:
  backend:  
    build: ./backend
    command: npm run start-server
    ports:
      - "3002:3002"
  frontend:
    build: 
      - dockerfile: ./frontend/Dockerfile
      - args:
          VITE_DATA_SERVER_URL: ${VITE_DATA_SERVER_URL}
    ports:
      - "3001:3001"
  
